# Flyway configuration - {{schema}} schema (DEV)

flyway.url=jdbc:mysql://{{devHost}}:3306/{{schema}}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone={{timezone}}
flyway.user={{devUser}}
flyway.password={{devPassword}}

# Migration script location for {{schema}} schema
flyway.locations=filesystem:src/main/resources/db/migration/{{schema}}

# Flyway tracks its history in this table inside the {{schema}} schema
flyway.table=flyway_schema_history

flyway.baselineOnMigrate=false
flyway.baselineVersion=0

flyway.outOfOrder=false
flyway.validateOnMigrate=true
